### ISSUE TITLE
Test 11983 problem

### ISSUE THREAD

**Issue by iheos** [usnistgov/iheos-toolkit2#135]
I ran test 11983 against your simulator (because I ran into a vendor issue).

The test has a submit step (no document) and a second submit step (missing metadata).

When I submit/missing metadata, the simulator returns the expected response code.

When I submit/missing document, we get something else.

This is not critical for me. I think you will want to review in advance of your next release. See attached screen capture. I can send you logs or whatever else you need if you want to explore further.

The response in the inspector is:

<rs:RegistryResponse status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure"
      xmlns:rs="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0">
   rs:RegistryErrorList
      <rs:RegistryError
            codeContext="No Message at gov.nist.toolkit.valregmsg.message.MultipartContainer.getContent(MultipartContainer.java:61) at gov.nist.toolkit.simulators.sim.rep.RepPnRSim.run(RepPnRSim.java:106) at gov.nist.toolkit.valsupport.engine.MessageValidatorEngine.run(MessageValidatorEngine.java:164) at gov.nist.toolkit.simulators.sim.rep.RepositoryActorSimulator.run(RepositoryActorSimulator.java:117) at gov.nist.toolkit.simulators.servlet.SimServlet.doPost(SimServlet.java:506)"
            errorCode="XDSRepositoryError"
            location=""
            severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"/>
   /rs:RegistryErrorList
/rs:RegistryResponse

I believe I configured this repository simulator to point to your public registry.

**Comment by iheos** [comment]
Solved.
