### ISSUE TITLE
Fix integration test failure on feature/repackage

### ISSUE THREAD

**Issue by skbhaskarla** [usnistgov/iheos-toolkit2#136]
Results :

Failed tests: 
  MultiQuerySpec.single rg:44 Condition not satisfied:

results.get(0).passed()
|       |      |
|       |      false
|       :test:
|       1:	  FAIL  [ Site bill__ig does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source)<br />	at gov.nist.toolkit.session.server.Session.setSiteSpec(Session.groovy:151)<br />	at gov.nist.toolkit.session.server.services.FindDocuments2.run(FindDocuments2.java:34)<br />	at gov.nist.toolkit.session.server.serviceManager.QueryServiceManager.findDocuments2(QueryServiceManager.java:311)<br />	at gov.nist.toolkit.services.server.ToolkitApi.findDocuments(ToolkitApi.java:254)<br />	at gov.nist.toolkit.services.server.ToolkitApi$findDocuments$1.call(Unknown Source) ][ null ]
[:test:
1:	  FAIL  [ Site bill__ig does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source)<br />	at gov.nist.toolkit.session.server.Session.setSiteSpec(Session.groovy:151)<br />	at gov.nist.toolkit.session.server.services.FindDocuments2.run(FindDocuments2.java:34)<br />	at gov.nist.toolkit.session.server.serviceManager.QueryServiceManager.findDocuments2(QueryServiceManager.java:311)<br />	at gov.nist.toolkit.services.server.ToolkitApi.findDocuments(ToolkitApi.java:254)<br />	at gov.nist.toolkit.services.server.ToolkitApi$findDocuments$1.call(Unknown Source) ][ null ]
]

  MultiQuerySpec.two rgs:68 Condition not satisfied:

results.get(0).passed()
|       |      |
|       |      false
|       :test:
|       1:	  FAIL  [ Site bill__ig does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source)<br />	at gov.nist.toolkit.session.server.Session.setSiteSpec(Session.groovy:151)<br />	at gov.nist.toolkit.session.server.services.FindDocuments2.run(FindDocuments2.java:34)<br />	at gov.nist.toolkit.session.server.serviceManager.QueryServiceManager.findDocuments2(QueryServiceManager.java:311)<br />	at gov.nist.toolkit.services.server.ToolkitApi.findDocuments(ToolkitApi.java:254)<br />	at gov.nist.toolkit.services.server.ToolkitApi$findDocuments$1.call(Unknown Source) ][ null ]
[:test:
1:	  FAIL  [ Site bill__ig does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source)<br />	at gov.nist.toolkit.session.server.Session.setSiteSpec(Session.groovy:151)<br />	at gov.nist.toolkit.session.server.services.FindDocuments2.run(FindDocuments2.java:34)<br />	at gov.nist.toolkit.session.server.serviceManager.QueryServiceManager.findDocuments2(QueryServiceManager.java:311)<br />	at gov.nist.toolkit.services.server.ToolkitApi.findDocuments(ToolkitApi.java:254)<br />	at gov.nist.toolkit.services.server.ToolkitApi$findDocuments$1.call(Unknown Source) ][ null ]
]

  QuerySpec.Test Responding Gateway:180 Condition not satisfied:

results.get(0).passed()
|       |      |
|       |      false
|       :test:
|       1:	  FAIL  [ Site bill__ig does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source)<br />	at gov.nist.toolkit.session.server.Session.setSiteSpec(Session.groovy:151)<br />	at gov.nist.toolkit.session.server.services.FindDocuments2.run(FindDocuments2.java:34)<br />	at gov.nist.toolkit.session.server.serviceManager.QueryServiceManager.findDocuments2(QueryServiceManager.java:311)<br />	at gov.nist.toolkit.services.server.ToolkitApi.findDocuments(ToolkitApi.java:254)<br />	at gov.nist.toolkit.services.server.ToolkitApi$findDocuments$2.call(Unknown Source) ][ null ]
[:test:
1:	  FAIL  [ Site bill__ig does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source)<br />	at gov.nist.toolkit.session.server.Session.setSiteSpec(Session.groovy:151)<br />	at gov.nist.toolkit.session.server.services.FindDocuments2.run(FindDocuments2.java:34)<br />	at gov.nist.toolkit.session.server.serviceManager.QueryServiceManager.findDocuments2(QueryServiceManager.java:311)<br />	at gov.nist.toolkit.services.server.ToolkitApi.findDocuments(ToolkitApi.java:254)<br />	at gov.nist.toolkit.services.server.ToolkitApi$findDocuments$2.call(Unknown Source) ][ null ]
]

  RegisterSpec.Run a failed test:122 Condition not satisfied:

results.get(0).passed()
|       |      |
|       |      false
|       :test:
|       1:	  FAIL  [ Site bill__reg does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source)<br />	at gov.nist.toolkit.session.server.Session.setSiteSpec(Session.groovy:151)<br />	at gov.nist.toolkit.session.server.serviceManager.TestRunner.run(TestRunner.java:40)<br />	at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.runMesaTest(XdsTestServiceManager.java:139)<br />	at gov.nist.toolkit.services.server.ToolkitApi.runTest(ToolkitApi.java:224)<br />	at gov.nist.toolkit.services.server.ToolkitApi$runTest$3.call(Unknown Source) ][ null ]
[:test:
1:	  FAIL  [ Site bill__reg does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source)<br />	at gov.nist.toolkit.session.server.Session.setSiteSpec(Session.groovy:151)<br />	at gov.nist.toolkit.session.server.serviceManager.TestRunner.run(TestRunner.java:40)<br />	at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.runMesaTest(XdsTestServiceManager.java:139)<br />	at gov.nist.toolkit.services.server.ToolkitApi.runTest(ToolkitApi.java:224)<br />	at gov.nist.toolkit.services.server.ToolkitApi$runTest$3.call(Unknown Source) ][ null ]
]

  RegisterSpec.Submit Pid transaction to Registry simulator:85 Condition not satisfied:

results.get(0).passed()
|       |      |
|       |      false
|       :test:
|       1:	  FAIL  [ Site bill__reg does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source) ][ null ]
[:test:
1:	  FAIL  [ Site bill__reg does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source) ][ null ]
]

  StoredQuerySpec.Run SQ initialization:123 Condition not satisfied:

results.get(0).passed()
|       |      |
|       |      false
|       :test:
|       1:	  FAIL  [ Site bill__reg does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source)<br />	at gov.nist.toolkit.session.server.Session.setSiteSpec(Session.groovy:151)<br />	at gov.nist.toolkit.session.server.serviceManager.TestRunner.run(TestRunner.java:40)<br />	at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.runMesaTest(XdsTestServiceManager.java:139)<br />	at gov.nist.toolkit.services.server.ToolkitApi.runTest(ToolkitApi.java:224)<br />	at gov.nist.toolkit.services.server.ToolkitApi$runTest$3.call(Unknown Source) ][ null ]
[:test:
1:	  FAIL  [ Site bill__reg does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source)<br />	at gov.nist.toolkit.session.server.Session.setSiteSpec(Session.groovy:151)<br />	at gov.nist.toolkit.session.server.serviceManager.TestRunner.run(TestRunner.java:40)<br />	at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.runMesaTest(XdsTestServiceManager.java:139)<br />	at gov.nist.toolkit.services.server.ToolkitApi.runTest(ToolkitApi.java:224)<br />	at gov.nist.toolkit.services.server.ToolkitApi$runTest$3.call(Unknown Source) ][ null ]
]

  StoredQuerySpec.Run SQ tests:139 Condition not satisfied:

results.get(0).passed()
|       |      |
|       |      false
|       :test:
|       1:	  FAIL  [ Site bill__reg does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source)<br />	at gov.nist.toolkit.session.server.Session.setSiteSpec(Session.groovy:151)<br />	at gov.nist.toolkit.session.server.serviceManager.TestRunner.run(TestRunner.java:40)<br />	at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.runMesaTest(XdsTestServiceManager.java:139)<br />	at gov.nist.toolkit.services.server.ToolkitApi.runTest(ToolkitApi.java:224)<br />	at gov.nist.toolkit.services.server.ToolkitApi$runTest$3.call(Unknown Source) ][ null ]
[:test:
1:	  FAIL  [ Site bill__reg does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source)<br />	at gov.nist.toolkit.session.server.Session.setSiteSpec(Session.groovy:151)<br />	at gov.nist.toolkit.session.server.serviceManager.TestRunner.run(TestRunner.java:40)<br />	at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.runMesaTest(XdsTestServiceManager.java:139)<br />	at gov.nist.toolkit.services.server.ToolkitApi.runTest(ToolkitApi.java:224)<br />	at gov.nist.toolkit.services.server.ToolkitApi$runTest$3.call(Unknown Source) ][ null ]
]

  StoredQuerySpec.Submit second Pid transaction to Registry simulator:107 Condition not satisfied:

results.get(0).passed()
|       |      |
|       |      false
|       :test:
|       1:	  FAIL  [ Site bill__reg does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source) ][ null ]
[:test:
1:	  FAIL  [ Site bill__reg does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source) ][ null ]
]

  OdRegistrySpec.Run all tests:100 Condition not satisfied:

results.get(0).passed()
|       |      |
|       |      false
|       :test:
|       1:	  FAIL  [ Site sunil__reg does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source)<br />	at gov.nist.toolkit.session.server.Session.setSiteSpec(Session.groovy:151)<br />	at gov.nist.toolkit.session.server.serviceManager.TestRunner.run(TestRunner.java:40)<br />	at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.runMesaTest(XdsTestServiceManager.java:139)<br />	at gov.nist.toolkit.services.server.ToolkitApi.runTest(ToolkitApi.java:224)<br />	at gov.nist.toolkit.services.server.ToolkitApi$runTest$4.call(Unknown Source) ][ null ]
[:test:
1:	  FAIL  [ Site sunil__reg does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source)<br />	at gov.nist.toolkit.session.server.Session.setSiteSpec(Session.groovy:151)<br />	at gov.nist.toolkit.session.server.serviceManager.TestRunner.run(TestRunner.java:40)<br />	at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.runMesaTest(XdsTestServiceManager.java:139)<br />	at gov.nist.toolkit.services.server.ToolkitApi.runTest(ToolkitApi.java:224)<br />	at gov.nist.toolkit.services.server.ToolkitApi$runTest$4.call(Unknown Source) ][ null ]
]

  OdRegistrySpec.Submit Pid transaction to Registry simulator:82 Condition not satisfied:

results.get(0).passed()
|       |      |
|       |      false
|       :test:
|       1:	  FAIL  [ Site sunil__reg does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source) ][ null ]
[:test:
1:	  FAIL  [ Site sunil__reg does not define an XDS.b Repository<br />	at gov.nist.toolkit.sitemanagement.client.Site$getRepositoryUniqueId$1.call(Unknown Source) ][ null ]
]

  RepSpec.12360:113 Condition not satisfied:

testOverviewDTO.pass
|               |
|               false
gov.nist.toolkit.session.client.TestOverviewDTO@427ae189

Tests run: 55, Failures: 11, Errors: 0, Skipped: 0

**Comment by skbhaskarla** [comment]
Seems to be already fixed by the latest code I pulled from feature/repackage.
