### ISSUE TITLE
Patient Manager throws exception when sending feed

### ISSUE THREAD

**Issue by iheos** [usnistgov/iheos-toolkit2#154]
When using the Patient Manager to send a V2 PIX Feed this error pops up

    Status: Failure
    UtilityRunner#run: session.xt not initialized
    Exception Exception
        at gov.nist.toolkit.session.server.serviceManager.UtilityRunner.run(UtilityRunner.java:64)
        at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.sendPidToRegistry(XdsTestServiceManager.java:1153)
        at gov.nist.toolkit.xdstools2.server.ToolkitServiceImpl.sendPidToRegistry(ToolkitServiceImpl.java:577)

**Comment by iheos** [comment]
Also requested is to make MSH-3,-4,-5,-6 configurable.
