### ISSUE TITLE
4.1.2 Find Documents Stored Query Utility Does Not Work for Me

### ISSUE THREAD

**Issue by stl-steve-moore** [usnistgov/iheos-toolkit2#155]
I loaded some sample documents into a Registry/Repository simulator. I then tried to use the FindDocuments tool (left tab, under Queries & Retrieves). When I entered a patient ID, selected the simulator and let it go, the software threw an exception.
![screen shot 2016-12-15 at 3 58 43 pm](https://cloud.githubusercontent.com/assets/889913/21243754/d3a66cac-c2df-11e6-9668-26c11d45c7b9.png)

Status: Failure
Not using TLS
Not using SAML
Site: steve__rr
Parameters:
...$object_types$: ('urn:uuid:7edca82f-054d-47f2-a032-9b2a5b5186c1')
...$patient_id$: 11990^^^&1.3.6.1.4.1.21367.2005.13.20.1000&ISO
Starting
**Path does not target contents of testkit**
Exception Exception
at gov.nist.toolkit.testenginelogging.TestLogDetails.getLogicalPath(TestLogDetails.java:142)
at gov.nist.toolkit.testenginelogging.TestLogDetails.getLogicalPath(TestLogDetails.java:137)
at gov.nist.toolkit.testengine.engine.TestKitLog.getLogFile(TestKitLog.java:31)
at gov.nist.toolkit.testengine.engine.XdsTest.runAndReturnLogs(XdsTest.java:528)
at gov.nist.toolkit.testengine.engine.Xdstest2.run(Xdstest2.java:265)
at gov.nist.toolkit.session.server.serviceManager.UtilityRunner.run(UtilityRunner.java:189)
at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.xdstest(XdsTestServiceManager.java:125)
at gov.nist.toolkit.session.server.services.FindDocuments.run(FindDocuments.java:50)
at gov.nist.toolkit.session.server.serviceManager.QueryServiceManager.findDocuments(QueryServiceManager.java:107)
at gov.nist.toolkit.xdstools2.server.ToolkitServiceImpl.findDocuments(ToolkitServiceImpl.java:225)

**Comment by iheos** [comment]
Fixed. Issue 163.
