### ISSUE TITLE
SiteLoaderTest unit test fails on Windows

### ISSUE THREAD

**Issue by skbhaskarla** [usnistgov/iheos-toolkit2#345]
SiteLoaderTest unit test fails on Windows due to file delete problem probably caused by an open file associated with the the XML stream reader.

Log (created using FileUtils.deleteDirectory(dir))

"Deleting all sites from test session "

java.io.IOException: Unable to delete file: C:\tk\xdstools2\target\test-classes\external_cache\actors\default\bob.xml

	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
	at gov.nist.toolkit.xdstools2.sites.SiteLoaderTest.deleteCommonSites(SiteLoaderTest.groovy:129)
	at gov.nist.toolkit.xdstools2.sites.SiteLoaderTest.setup(SiteLoaderTest.groovy:36)

gov.nist.toolkit.utilities.xml#parse_xml(File infile) 
 

SiteLoaderTest# 'foo testsession reports foo and default repositories' failed because the site, "bob", from the previous test method still existed and it failed the equality check on Line 93.

**Comment by skbhaskarla** [comment]
Fixed 
https://github.com/usnistgov/iheos-toolkit2/commit/71b9d849e18bb79386fd214b76e3cdd2b9216852
