### ISSUE TITLE
FHIR Server produces BindException on Webapp StartUp

### ISSUE THREAD

**Issue by luettmann** [usnistgov/iheos-toolkit2#353]
After deploying the XDS Toolkit a BindException occurs in the Tomcat log files blocking all request to other simulators. When deleting the FHIR Server simulator its shows up again after reloading the XDS Toolkit page.

The stacktrace is as follows:
09-Apr-2018 12:13:33.028 SEVERE [localhost-startStop-2] org.apache.catalina.core.StandardContext.loadOnStartup Servlet [simulatorServlet] in web application [/xdstools610] threw load() exception
 java.net.BindException: Address already in use: JVM_Bind
	at java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
	at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.net.PlainSocketImpl.bind(Unknown Source)
	at java.net.ServerSocket.bind(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at gov.nist.toolkit.fhir.simulators.proxy.service.RequestListenerThread.<init>(RequestListenerThread.java:46)
	at gov.nist.toolkit.fhir.simulators.proxy.service.ElementalReverseProxy.start(ElementalReverseProxy.java:63)
	at gov.nist.toolkit.fhir.simulators.proxy.service.ElementalReverseProxy.start(ElementalReverseProxy.java:70)
	at gov.nist.toolkit.fhir.simulators.servlet.SimServlet.init(SimServlet.java:98)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4997)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5289)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1795)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by iheos** [comment]
Toolkit uses three ports.  One of them is used for the Proxy that fronts
the FHIR services.  In the distributions this is identified in
toolkit.properties as

Proxy_Port=7297

A bind exception means that Toolkit is trying to use a port that is already
"in use". If this port is already used in your system then change this
property and restart.  Toolkit will use the port you configure.

Toolkit.properties resides in

WEB-INF/classes.toolkit.properties
