### ISSUE TITLE
xdstools 6.2.0:  String '--' not allowed in comment

### ISSUE THREAD

**Issue by kevingill1966** [usnistgov/iheos-toolkit2#354]
I downloaded xdstools 6.2.0 and started it in a new docker instance. The following error messages are displayed in the logs during startup. Later when I try to run my tests, similar errors are displayed on the browser.

============= tomcat log on startup =====================================

site is default/default__fhir_support
default/default__fhir_support
Collection Name: default__fhir_support
Transactions:
	[trans=fhir ActorType=? isSecure=false isAsync=false] : http://localhost:8080/xdstools6/fsim/default__fhir_support/fhir

java.lang.Exception: Site default__fhir_support does not define an XDS.b Repository
[com.ctc.wstx.exc.WstxLazyException] String '--' not allowed in comment (missing '>'?)
 at [row,col {unknown-source}]: [5,3]
Exception WstxLazyException
	at gov.nist.toolkit.utilities.xml.XmlFileStream.parse_xml(XmlFileStream.java:42)
	at gov.nist.toolkit.utilities.xml.Util.parse_xml(Util.java:66)
	at gov.nist.toolkit.session.server.CodesConfigurationBuilder.<init>(CodesConfigurationBuilder.java:30)
	at gov.nist.toolkit.session.server.Session.getCodesConfiguration(Session.groovy:537)
	at gov.nist.toolkit.session.server.Session.currentCodesConfiguration(Session.groovy:546)
	at gov.nist.toolkit.session.server.serviceManager.UtilityRunner.run(UtilityRunner.java:64)
	at gov.nist.toolkit.session.server.serviceManager.TestRunner.run(TestRunner.java:89)
	at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.runMesaTest(XdsTestServiceManager.java:142)
	at gov.nist.toolkit.services.server.ToolkitApi.runTest(ToolkitApi.java:244)
	at gov.nist.toolkit.services.server.ToolkitApi$runTest$3.call(Unknown Source)
	at gov.nist.toolkit.services.server.orchestration.Util.submit(Util.groovy:75)
	at gov.nist.toolkit.services.server.orchestration.Util$submit.call(Unknown Source)
	at gov.nist.toolkit.services.server.orchestration.FhirSupportOrchestrationBuilder.buildTestEnvironment(FhirSupportOrchestrationBuilder.groovy:95)
	at gov.nist.toolkit.services.server.orchestration.FhirSupportOrchestrationBuilder$buildTestEnvironment.call(Unknown Source)
	at gov.nist.toolkit.services.server.orchestration.OrchestrationManager.buildFhirSupportEnvironment(OrchestrationManager.groovy:178)
	at gov.nist.toolkit.services.server.orchestration.OrchestrationManager$buildFhirSupportEnvironment.call(Unknown Source)
	at gov.nist.toolkit.toolkitServices.httpApi.ToolkitServicesStartup$Init.run(ToolkitServicesStartup.groovy:34)
Persist results to EC
Error submiting Patients to FHIR server default__fhir_support 
 :supporting_fhir_patients:  in default
1:	  FAIL  [ [com.ctc.wstx.exc.WstxLazyException] String '--' not allowed in comment (missing '>'?)<br /> at [row,col {unknown-source}]: [5,3]<br />Exception WstxLazyException<br />	at gov.nist.toolkit.utilities.xml.XmlFileStream.parse_xml(XmlFileStream.java:42)<br />	at gov.nist.toolkit.utilities.xml.Util.parse_xml(Util.java:66)<br />	at gov.nist.toolkit.session.server.CodesConfigurationBuilder.<init>(CodesConfigurationBuilder.java:30)<br />	at gov.nist.toolkit.session.server.Session.getCodesConfiguration(Session.groovy:537)<br />	at gov.nist.toolkit.session.server.Session.currentCodesConfiguration(Session.groovy:546)<br />	at gov.nist.toolkit.session.server.serviceManager.UtilityRunner.run(UtilityRunner.java:64)<br />	at gov.nist.toolkit.session.server.serviceManager.TestRunner.run(TestRunner.java:89)<br />	at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.runMesaTest(XdsTestServiceManager.java:142)<br />	at gov.nist.toolkit.services.server.ToolkitApi.runTest(ToolkitApi.java:244)<br />	at gov.nist.toolkit.services.server.ToolkitApi$runTest$3.call(Unknown Source)<br />	at gov.nist.toolkit.services.server.orchestration.Util.submit(Util.groovy:75)<br />	at gov.nist.toolkit.services.server.orchestration.Util$submit.call(Unknown Source)<br />	at gov.nist.toolkit.services.server.orchestration.FhirSupportOrchestrationBuilder.buildTestEnvironment(FhirSupportOrchestrationBuilder.groovy:95)<br />	at gov.nist.toolkit.services.server.orchestration.FhirSupportOrchestrationBuilder$buildTestEnvironment.call(Unknown Source)<br />	at gov.nist.toolkit.services.server.orchestration.OrchestrationManager.buildFhirSupportEnvironment(OrchestrationManager.groovy:178)<br />	at gov.nist.toolkit.services.server.orchestration.OrchestrationManager$buildFhirSupportEnvironment.call(Unknown Source)<br />	at gov.nist.toolkit.toolkitServices.httpApi.ToolkitServicesStartup$Init.run(ToolkitServicesStartup.groovy:34) ][ null ]

Exception Exception
	1:	  FAIL  [ [com.ctc.wstx.exc.WstxLazyException] String '--' not allowed in comment (missing '>'?)<br /> at [row,col {unknown-source}]: [5,3]<br />Exception WstxLazyException<br />	at gov.nist.toolkit.utilities.xml.XmlFileStream.parse_xml(XmlFileStream.java:42)<br />	at gov.nist.toolkit.utilities.xml.Util.parse_xml(Util.java:66)<br />	at gov.nist.toolkit.session.server.CodesConfigurationBuilder.<init>(CodesConfigurationBuilder.java:30)<br />	at gov.nist.toolkit.session.server.Session.getCodesConfiguration(Session.groovy:537)<br />	at gov.nist.toolkit.session.server.Session.currentCodesConfiguration(Session.groovy:546)<br />	at gov.nist.toolkit.session.server.serviceManager.UtilityRunner.run(UtilityRunner.java:64)<br />	at gov.nist.toolkit.session.server.serviceManager.TestRunner.run(TestRunner.java:89)<br />	at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.runMesaTest(XdsTestServiceManager.java:142)<br />	at gov.nist.toolkit.services.server.ToolkitApi.runTest(ToolkitApi.java:244)<br />	at gov.nist.toolkit.services.server.ToolkitApi$runTest$3.call(Unknown Source)<br />	at gov.nist.toolkit.services.server.orchestration.Util.submit(Util.groovy:75)<br />	at gov.nist.toolkit.services.server.orchestration.Util$submit.call(Unknown Source)<br />	at gov.nist.toolkit.services.server.orchestration.FhirSupportOrchestrationBuilder.buildTestEnvironment(FhirSupportOrchestrationBuilder.groovy:95)<br />	at gov.nist.toolkit.services.server.orchestration.FhirSupportOrchestrationBuilder$buildTestEnvironment.call(Unknown Source)<br />	at gov.nist.toolkit.services.server.orchestration.OrchestrationManager.buildFhirSupportEnvironment(OrchestrationManager.groovy:178)<br />	at gov.nist.toolkit.services.server.orchestration.OrchestrationManager$buildFhirSupportEnvironment.call(Unknown Source)<br />at gov.nist.toolkit.toolkitServices.httpApi.ToolkitServicesStartup$Init.run(ToolkitServicesStartup.groovy:34) ][ null ]
	at gov.nist.toolkit.services.server.orchestration.Util.submit(Util.groovy:77)
	at gov.nist.toolkit.services.server.orchestration.Util$submit.call(Unknown Source)
	at gov.nist.toolkit.services.server.orchestration.FhirSupportOrchestrationBuilder.buildTestEnvironment(FhirSupportOrchestrationBuilder.groovy:95)
	at gov.nist.toolkit.services.server.orchestration.FhirSupportOrchestrationBuilder$buildTestEnvironment.call(Unknown Source)
	at gov.nist.toolkit.services.server.orchestration.OrchestrationManager.buildFhirSupportEnvironment(OrchestrationManager.groovy:178)
	at gov.nist.toolkit.services.server.orchestration.OrchestrationManager$buildFhirSupportEnvironment.call(Unknown Source)
	at gov.nist.toolkit.toolkitServices.httpApi.ToolkitServicesStartup$Init.run(ToolkitServicesStartup.groovy:34)
FHIR Support Server was not started
MessageValidatorFactory()
Session 1670D3ADF9A51ADBB3EAC3F7058AD705 started
Context Path is /xdstools6

==================== browser error ====================================

Error: [com.ctc.wstx.exc.WstxLazyException] String '--' not allowed in comment (missing '>'?) at [row,col {unknown-source}]: [5,3]

[com.ctc.wstx.exc.WstxLazyException] com.ctc.wstx.exc.WstxParsingException: String '--' not allowed in comment (missing '>'?)
at [row,col {unknown-source}]: [5,3]
at com.ctc.wstx.exc.WstxLazyException.throwLazily(WstxLazyException.java:45)
at com.ctc.wstx.sr.StreamScanner.throwLazyError(StreamScanner.java:729)
at com.ctc.wstx.sr.BasicStreamReader.safeFinishToken(BasicStreamReader.java:3659)
at com.ctc.wstx.sr.BasicStreamReader.getText(BasicStreamReader.java:809)
at org.apache.axiom.om.impl.builder.StAXOMBuilder.createComment(StAXOMBuilder.java:471)
at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:276)
at org.apache.axiom.om.impl.llom.OMDocumentImpl.getOMDocumentElement(OMDocumentImpl.java:104)
at org.apache.axiom.om.impl.builder.StAXOMBuilder.getDocumentElement(StAXOMBuilder.java:568)
at gov.nist.toolkit.utilities.xml.XmlFileStream.parse_xml(XmlFileStream.java:42)
at gov.nist.toolkit.utilities.xml.Util.parse_xml(Util.java:66)
at gov.nist.toolkit.session.server.CodesConfigurationBuilder.(CodesConfigurationBuilder.java:30)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at gov.nist.toolkit.session.server.Session.getCodesConfiguration(Session.groovy:537)
at gov.nist.toolkit.session.server.Session.currentCodesConfiguration(Session.groovy:546)
at gov.nist.toolkit.session.server.Session.getAssigningAuthority(Session.groovy:552)
at gov.nist.toolkit.session.server.Session.allocateNewPid(Session.groovy:525)
at gov.nist.toolkit.services.server.orchestration.OrchestrationProperties.allocatePids(OrchestrationProperties.java:43)
at gov.nist.toolkit.services.server.orchestration.OrchestrationProperties.(OrchestrationProperties.java:36)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
at gov.nist.toolkit.services.server.orchestration.IgOrchestrationBuilder.buildTestEnvironment(IgOrchestrationBuilder.groovy:53)
at gov.nist.toolkit.services.server.orchestration.IgOrchestrationBuilder$buildTestEnvironment.call(Unknown Source)
at gov.nist.toolkit.services.server.orchestration.OrchestrationManager.buildIgTestEnvironment(OrchestrationManager.groovy:24)
at gov.nist.toolkit.xdstools2.server.ToolkitServiceImpl.buildIgTestOrchestration(ToolkitServiceImpl.java:565)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.ctc.wstx.exc.WstxParsingException: String '--' not allowed in comment (missing '>'?)
at [row,col {unknown-source}]: [5,3]
at com.ctc.wstx.sr.StreamScanner.constructWfcException(StreamScanner.java:630)
at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:461)
at com.ctc.wstx.sr.BasicStreamReader.readComment2(BasicStreamReader.java:3869)
at com.ctc.wstx.sr.BasicStreamReader.readComment(BasicStreamReader.java:3825)
at com.ctc.wstx.sr.BasicStreamReader.finishToken(BasicStreamReader.java:3724)
at com.ctc.wstx.sr.BasicStreamReader.safeFinishToken(BasicStreamReader.java:3649)
... 64 more

**Comment by iheos** [comment]
Fixed.  Will be updated in 6.2.1. later today.  To fix locally edit
toolkitx/environment/default/codes.xml.  The problem is on line 5.

**Comment by kevingill1966** [comment]
I made the change in codes.xml, and restarted. (I am trying to run the network affinity tests). I get this error now.


Running test from /usr/local/tomcat/webapps/xdstools6/toolkitx/testkit/tests/15824
....

Sending Patient ID null to localhost:5002...
Have incoming request
...no errors
BasicContext getRetrievedDocumentsModel step_id ==> step
BasicContext getRetrievedDocumentsModel step_id ==> step
Error: stepId=step : No Message
Exception NullPointerException
    at gov.nist.toolkit.adt.AdtSender.send(AdtSender.java:59)
    at gov.nist.toolkit.adt.A01Sender.send(A01Sender.java:44)
    at gov.nist.toolkit.testengine.transactions.PatientIdentityFeedTransaction.run(PatientIdentityFeedTransaction.java:59)
    at gov.nist.toolkit.testengine.transactions.BasicTransaction.doRun(BasicTransaction.java:218)
    at gov.nist.toolkit.testengine.engine.StepContext.run(StepContext.java:444)
    at gov.nist.toolkit.testengine.engine.PlanContext.run(PlanContext.java:251)
    at gov.nist.toolkit.testengine.engine.XdsTest.runAndReturnLogs(XdsTest.java:220)
    at gov.nist.toolkit.testengine.engine.Xdstest2.run(Xdstest2.java:266)
    at gov.nist.toolkit.session.server.serviceManager.UtilityRunner.getResult(UtilityRunner.java:168)
    at gov.nist.toolkit.session.server.serviceManager.UtilityRunner.run(UtilityRunner.java:133)
    at gov.nist.toolkit.session.server.serviceManager.TestRunner.run(TestRunner.java:89)
    at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.runTest(XdsTestServiceManager.java:154)
    at gov.nist.toolkit.xdstools2.server.ToolkitServiceImpl.runTest(ToolkitServiceImpl.java:772)
No Message

This is probably caused by the system no initialising properly. I will re-create it when 6.2.1 is available and  try again. Thanks

**Comment by iheos** [comment]
Fixed
