### ISSUE TITLE
Orchestration failed because internal test cannot be found when Ignore_internal_testkit is True

### ISSUE THREAD

**Issue by skbhaskarla** [usnistgov/iheos-toolkit2#420]
Steps to reproduce the responding gateway orchestration error:
1) Set Ignore_internal_testkit=true in Toolkit Configuration (assuming you have tests in your local test kit)
2) Re-initialize RG gateway
3) Notice the error below

Initialization of dev__rg failed:
:12318: in dev
1:	FAIL [ Test :12318: in dev not found
Exception Exception
at gov.nist.toolkit.session.server.serviceManager.UtilityRunner.run(UtilityRunner.java:99)
at gov.nist.toolkit.session.server.serviceManager.TestRunner.run(TestRunner.java:89)
at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.runMesaTest(XdsTestServiceManager.java:143)
at gov.nist.toolkit.services.server.ToolkitApi.runTest(ToolkitApi.java:244)
at gov.nist.toolkit.services.server.ToolkitApi$runTest$3.call(Unknown Source)
at gov.nist.toolkit.services.server.orchestration.Util.submit(Util.groovy:53)
at gov.nist.toolkit.services.server.orchestration.Util$submit$0.call(Unknown Source)
at gov.nist.toolkit.services.server.orchestration.RgOrchestrationBuilder.buildTestEnvironment(RgOrchestrationBuilder.groovy:157)
at gov.nist.toolkit.services.server.orchestration.RgOrchestrationBuilder$buildTestEnvironment.call(Unknown Source)
at gov.nist.toolkit.services.server.orchestration.OrchestrationManager.buildRgTestEnvironment(OrchestrationManager.groovy:52)
at gov.nist.toolkit.xdstools2.server.ToolkitServiceImpl.buildRgTestOrchestration(ToolkitServiceImpl.java:631) ][ null ]

**Comment by skbhaskarla** [comment]
This may also affect FHIR Support Server in development mode. I was able to get around this problem by 
1) Deleting default\default__fhir_support
2) Recompiling Toolkit with Ignore_internal_testkit=false
3) Restart Toolkit
