### ISSUE TITLE
xdstoolkit error - FileNotFoundException 

### ISSUE THREAD

**Issue by Veltarn** [usnistgov/iheos-toolkit2#458]
Hi,

I installed xdstoolkit 7.1.0 inside à Docker tomcat container.
I've created the External cache path and configured it inside the Toolkit configuration menu.
Once i've done it, when I navigate in this page, I got the following error:
![image](https://user-images.githubusercontent.com/6717266/54263631-91212400-4571-11e9-9cda-d73ccee949d3.png)

There is also the following stackstrace in the application's logs:

```
com.google.gwt.user.client.rpc.SerializationException: Type 'java.io.FileNotFoundException' was not included in the set of types which can be serialized by this SerializationPolicy or its Class object could not be loaded. For security purposes, this type will not be serialized.: instance = java.io.FileNotFoundException: /var/cache/xdstoolkit/TestSessionMgmt/default/policy.properties (No such file or directory)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serialize(ServerSerializationStreamWriter.java:696)
	at com.google.gwt.user.client.rpc.impl.AbstractSerializationStreamWriter.writeObject(AbstractSerializationStreamWriter.java:130)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter$ValueWriter$8.write(ServerSerializationStreamWriter.java:167)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serializeValue(ServerSerializationStreamWriter.java:606)
	at com.google.gwt.user.server.rpc.RPC.encodeResponse(RPC.java:644)
	at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:419)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2575)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2564)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

When I list the External cache directory content, I see a bunch of directories that seems to be accurate with what the application expects:

```
/usr/local/tomcat/bin # ls -l /var/cache/xdstoolkit/
total 0
drwxr-xr-x    3 root     root            21 Mar 12 22:44 TestLogCache
drwxr-xr-x    2 root     root             6 Mar 13 08:14 TestSessionMgmt
drwxr-xr-x    3 root     root            21 Mar 12 22:44 actors
drwxr-xr-x    6 root     root            52 Mar 12 22:42 datasets
drwxr-xr-x    4 root     root            38 Mar 12 22:42 environment
drwxr-xr-x    3 root     root            69 Mar 12 22:42 resourceCache
drwxr-xr-x    3 root     root            21 Mar 12 22:44 simdb
```

However, if I navigate inside each directory, there is a default subdir for each but nothing inside.

Is there anything I can do to fix this?
I will try to install it on a regular VM tonight to figure out if it's due to the container even tho I doubt.

**Comment by skbhaskarla** [comment]
Do you have the read/write "rw" flag set on your External Cache mapping part of your Docker command? Please see the External Cache part mentioned in https://github.com/usnistgov/iheos-toolkit2/wiki/Toolkit-on-Docker#docker-command-explained

In your case I think it should be "-v /var/cache/xdstoolkit:/var/cache/xdstoolkit:**rw**"

**Comment by Veltarn** [comment]
Yes, i've tried this without success

**Comment by skbhaskarla** [comment]
You may want to empty out your External Cache and try again. In other words, your External Cache should have no subfolders. The Toolkit startup will recreate all the directories. Let us know if this works. Also, it will be helpful for us to see the complete log and the full Docker run command you are using.

**Comment by Veltarn** [comment]
Ok so I tried again from scratch (container and image deletion and restart from zero).
I start with a /var/cache/xdstoolkit directory completely empty.
At first, I go to Toolkit configuration and change the default value which is at the moment _/path/to/the/external/cache_ to _/var/cache/xdstoolkit_

Once I've changed the value, I immediately see 6 subdirs being created in _/var/cache/xdstoolkit_
If I reload the page from this moment and I go to Toolkit configuration, I got the error message you've seen above (error 500...).

Now, if I remove the content of _/var/cache/xdstoolkit_ without restarting Tomcat, I have this error message:
![image](https://user-images.githubusercontent.com/6717266/54315068-8a2ffb00-45dd-11e9-925e-d071570f54ac.png)
If I restart Tomcat (or the container), the subdirs are re-created but not sub-subdirs which leads to the first issue.

Attached, Tomcat and xdstoolkit logs

Thanks for your reading

[tomcat.log](https://github.com/usnistgov/iheos-toolkit2/files/2963704/tomcat.log)
[xdstoolkit_app.log](https://github.com/usnistgov/iheos-toolkit2/files/2963705/xdstoolkit_app.log)

**Comment by skbhaskarla** [comment]
I didn't see anything in the logs to figure out the problem. 

But as a test from my side, here's what I did to install Toolkit on Docker (on Ubuntu). 
1. Download the latest Toolkit 7.1.1 war file. 
2. Run the following Docker command. Notice the two local file paths I am using. First is the External Cache, and next is the "myWebapps" folder, which contains the war file I downloaded. 

sudo docker run -it --rm \
-p 8080:8080 \
-p 5000-5015:5000-5015 \
-p 7297:7297 \
-p 8443:8443 \
-v /home/sunil/myDocker/ec_dir:/path/to/my/external/cache:rw \
-v /home/sunil/myDocker/myWebapps:/usr/local/tomcat/webapps:rw \
tomcat:7-jre8

This worked for me. I did not get any Toolkit errors.

Given the Docker run command above, can you spot any problems with the Docker run command you're using?

**Comment by Veltarn** [comment]
Hi,

So... I tried your exact command and it worked and I figured out the origin of the problem..
Apparently, the properties files inside the .war that holds the External cache path configuration must be changed before the very first boot of Tomcat.

In other words (and as the documentation tells it..), if you want to change the external cache path, you must download the sources, change this property and build xdstool with Maven.

It now works for my, sorry for the inconvenience and thanks for your time, it greatly helped me!
