### ISSUE TITLE
emun QuickScanLogAttribute created without proper serialization enabled

### ISSUE THREAD

**Issue by iheos** [usnistgov/iheos-toolkit2#465]
I have tried the 7.1.1 release, but after starting I get errors:

********************

2019-03-15T15:06:43,967 ERROR [ajp-nio-8010-exec-12] org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/xdstools]#log(182) - toolkitServlet: An IncompatibleRemoteServiceException was thrown while processing this call.

com.google.gwt.user.client.rpc.IncompatibleRemoteServiceException: Type '[Lgov.nist.toolkit.testenginelogging.client.QuickScanLogAttribute;' was not assignable to 'com.google.gwt.user.client.rpc.IsSerializable' and did not have a custom field serializer. For security purposes, this type will not be deserialized.

        at com.google.gwt.user.server.rpc.RPC.decodeRequest(RPC.java:323) ~[gwt-servlet-2.8.0.jar:?]

        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:296) [gwt-servlet-2.8.0.jar:?]

        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373) [gwt-servlet-2.8.0.jar:?]

        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62) [gwt-servlet-2.8.0.jar:?]

        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) [servlet-api.jar:?]

        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:?]

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.37]

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.37]

        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.37]

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.37]

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.37]

        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [catalina.jar:8.5.37]

        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.37]

        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [catalina.jar:8.5.37]

        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.37]

        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.37]

        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) [catalina.jar:8.5.37]

        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.37]

        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [catalina.jar:8.5.37]

        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:479) [tomcat-coyote.jar:8.5.37]

        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.37]

        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-coyote.jar:8.5.37]

        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-coyote.jar:8.5.37]

        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.37]

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]

        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.37]

        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]

Caused by: com.google.gwt.user.client.rpc.SerializationException: Type '[Lgov.nist.toolkit.testenginelogging.client.QuickScanLogAttribute;' was not assignable to 'com.google.gwt.user.client.rpc.IsSerializable' and did not have a custom field serializer. For security purposes, this type will not be deserialized.

        at com.google.gwt.user.server.rpc.impl.LegacySerializationPolicy.validateDeserialize(LegacySerializationPolicy.java:128) ~[gwt-servlet-2.8.0.jar:?]

        at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.deserialize(ServerSerializationStreamReader.java:676) ~[gwt-servlet-2.8.0.jar:?]

        at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.readObject(ServerSerializationStreamReader.java:592) ~[gwt-servlet-2.8.0.jar:?]

        at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader$ValueReader$8.readValue(ServerSerializationStreamReader.java:149) ~[gwt-servlet-2.8.0.jar:?]

        at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.deserializeValue(ServerSerializationStreamReader.java:434) ~[gwt-servlet-2.8.0.jar:?]

        at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.deserializeClass(ServerSerializationStreamReader.java:833) ~[gwt-servlet-2.8.0.jar:?]

        at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.deserializeImpl(ServerSerializationStreamReader.java:906) ~[gwt-servlet-2.8.0.jar:?]

        at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.deserialize(ServerSerializationStreamReader.java:687) ~[gwt-servlet-2.8.0.jar:?]

        at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.readObject(ServerSerializationStreamReader.java:592) ~[gwt-servlet-2.8.0.jar:?]

        at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader$ValueReader$8.readValue(ServerSerializationStreamReader.java:149) ~[gwt-servlet-2.8.0.jar:?]

        at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.deserializeValue(ServerSerializationStreamReader.java:434) ~[gwt-servlet-2.8.0.jar:?]

        at com.google.gwt.user.server.rpc.RPC.decodeRequest(RPC.java:312) ~[gwt-servlet-2.8.0.jar:?]

********************

**Comment by Thopap** [comment]
Hello Bill,

i have tried 7.2.0 and the issue above is away, but now another serialization failure occure:
`INFO   | jvm 1    | 2019/03/28 08:16:35 | 2019-03-28T08:16:35,933 ERROR [ajp-nio-8010-exec-11] org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/xdstools](182) - Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2019/03/28 08:16:35 | com.google.gwt.user.client.rpc.SerializationException: Type 'gov.nist.toolkit.services.client.PifType' was not assignable to 'com.google.gwt.user.client.rpc.IsSerializable' and did not have a custom field serializer.For security purposes, this type will not be serialized.: instance = V2
INFO   | jvm 1    | 2019/03/28 08:16:35 |       at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serialize(ServerSerializationStreamWriter.java:696) ~[gwt-servlet-2.8.0.jar:?]
INFO   | jvm 1    | 2019/03/28 08:16:35 |       at com.google.gwt.user.client.rpc.impl.AbstractSerializationStreamWriter.writeObject(AbstractSerializationStreamWriter.java:130) ~[gwt-servlet-2.8.0.jar:?]
INFO   | jvm 1    | 2019/03/28 08:16:35 |       at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter$ValueWriter$8.write(ServerSerializationStreamWriter.java:167) ~[gwt-servlet-2.8.0.jar:?]
INFO   | jvm 1    | 2019/03/28 08:16:35 |       at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serializeValue(ServerSerializationStreamWriter.java:606) ~[gwt-servlet-2.8.0.jar:?]
INFO   | jvm 1    | 2019/03/28 08:16:35 |       at com.google.gwt.user.server.rpc.RPC.encodeResponse(RPC.java:644) ~[gwt-servlet-2.8.0.jar:?]
INFO   | jvm 1    | 2019/03/28 08:16:35 |       at com.google.gwt.user.server.rpc.RPC.encodeResponseForSuccess(RPC.java:497) ~[gwt-servlet-2.8.0.jar:?]
INFO   | jvm 1    | 2019/03/28 08:16:35 |       at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:589) ~[gwt-servlet-2.8.0.jar:?]
I`

Is this the same or a similar issue?

**Comment by Mo-la-machette** [comment]
Hello, 

Release Note v7.2.1 specifies that bug fix is corrected (for PifType). But it seems bug fix is in branch develop but develop wasn't not merged into master for release v7.2.1

Best Regards,
Thomas
