### ISSUE TITLE
Base64 Decoding error when running under Java 16

### ISSUE THREAD

**Issue by aschnab** [usnistgov/iheos-toolkit2#529]
When running XDSToolkit under Java 16, and trying to do an operation which requires Base64 decoding (e.g. reading DICOM image data in a RAD-69 response), the operation fails. For instance, I tried running the test case "ids_2018-4803a - RAD-69: SOAP Retrieve for Single Image Study", Section "ValdateReturnedImages" of the XDS-I.b Imaging Document Source conformance tests, or using the "XDS.b_Doc_Source_Stores_Document" connectathon tool to retrieve a previously submitted document from a simulator.

I get the following error message - in the XDS.b_Doc_Source_Stores_Document tool, the message is presented to me right away, while in the conformance test, I can find a similar message using the result inspector.

```
sun/misc/BASE64Decoder
Exception NoClassDefFoundError
at gov.nist.toolkit.registrymsg.repository.Mtom.decode(Mtom.groovy:39)
at gov.nist.toolkit.registrymsg.repository.Mtom$decode.call(Unknown Source)
at gov.nist.toolkit.registrymsg.repository.RetrieveResponseParser.run(RetrieveResponseParser.groovy:56)
at gov.nist.toolkit.registrymsg.repository.RetrieveResponseParser.get(RetrieveResponseParser.groovy:26)
at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.buildResult(XdsTestServiceManager.java:1120)
at gov.nist.toolkit.session.server.serviceManager.UtilityRunner.getResult(UtilityRunner.java:176)
at gov.nist.toolkit.session.server.serviceManager.UtilityRunner.run(UtilityRunner.java:133)
at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.xdstest(XdsTestServiceManager.java:117)
at gov.nist.toolkit.session.server.services.SrcStoresDocVal.run(SrcStoresDocVal.java:36)
at gov.nist.toolkit.session.server.serviceManager.QueryServiceManager.srcStoresDocVal(QueryServiceManager.java:232)
at gov.nist.toolkit.xdstools2.server.ToolkitServiceImpl.srcStoresDocVal(ToolkitServiceImpl.java:447)
```

**Comment by stl-steve-moore** [comment]
That sounds like an environment issue. Are you running the toolkit locally or using a version that is online somewhere? If local, can you tell us:
* Operating system
* Tomcat version
* Java source and version (Oracle, ...?)

**Comment by aschnab** [comment]
Dear Steve,

* The Java version is 16 (this seems essential to produce the error; under Java 8, everything works as it should; this also seems consistent with `sun/misc/BASE64Decoder` pointing to the JDK's internal API); specifically, we used AdoptOpenJDK-16.0.1+9
* The operating system used on our system is CentOS 8.3
* The tomcat version used on our system is tomcat-9.0.43
