### ISSUE TITLE
XDS tools error: Message Validator named MultipartContainer does not exist

### ISSUE THREAD

**Issue by ihanbali** [usnistgov/iheos-toolkit2#552]
Hi
I installed XDS tools 7.2.2 and deployed it in Apache tomcat v 9.0.62
I defined document repository simulator
when I send PnR request with inline document to the simulator, it reports the following error:
Message Validator named MultipartContainer does not exist
Exception ToolkitRuntimeException
	gov.nist.toolkit.xdsexception.client.ToolkitRuntimeException: Message Validator named MultipartContainer does not exist
	at gov.nist.toolkit.valsupport.engine.MessageValidatorEngine.findMessageValidator(MessageValidatorEngine.java:94)
	at gov.nist.toolkit.valregmsg.message.DocumentElementValidator.run(DocumentElementValidator.java:26)
	at gov.nist.toolkit.valsupport.engine.MessageValidatorEngine.run(MessageValidatorEngine.java:165)
	at gov.nist.toolkit.validatorsSoapMessage.engine.ValidateMessageService.runValidation(ValidateMessageService.java:56)
	at gov.nist.toolkit.fhir.simulators.support.DsSimCommon.runValidation(DsSimCommon.java:232)
	at gov.nist.toolkit.fhir.simulators.support.DsSimCommon.runInitialValidations(DsSimCommon.java:202)
	at gov.nist.toolkit.fhir.simulators.support.DsSimCommon.runInitialValidationsAndFaultIfNecessary(DsSimCommon.java:195)
	at gov.nist.toolkit.fhir.simulators.sim.rep.RepositoryActorSimulator.run(RepositoryActorSimulator.java:115)
	at gov.nist.toolkit.fhir.simulators.servlet.SimServlet.doPost(SimServlet.java:700)
	at gov.nist.toolkit.fhir.simulators.servlet.SimServletFilter.doFilter(SimServletFilter.java:39)

Any idea what is wrong

**Comment by skbhaskarla** [comment]
Hi @Ihanbali,

This space is only to report confirmed bugs, not for general questions. The IHE XDS Google Groups would have a wider audience.

I think you meant XDS tools 7.7.2, if not, you should be using the latest release.

Regards,
Sunil

**Comment by ihanbali** [comment]
Thank you Sunil
Yes I meant XDS tools 7.7.2.
I will resume this issue in the XDS implementers group.
